build:
	GOOS=linux GOARCH=amd64 go build -o bin/grpc ${GOPATH}/src/github.com/tony612/envoy-drain-debug/greeter_grpc
	GOOS=linux GOARCH=amd64 go build -o bin/http ${GOPATH}/src/github.com/tony612/envoy-drain-debug/greeter_http
